export const fontesJuridicas = [
  // TJs
  { nome: "TJAC - Tribunal de Justiça do Acre", url: "https://www.tjac.jus.br" },
  { nome: "TJAL - Tribunal de Justiça de Alagoas", url: "https://www.tjal.jus.br" },
  { nome: "TJAM - Tribunal de Justiça do Amazonas", url: "https://www.tjam.jus.br" },
  { nome: "TJAP - Tribunal de Justiça do Amapá", url: "https://www.tjap.jus.br" },
  { nome: "TJBA - Tribunal de Justiça da Bahia", url: "https://www.tjba.jus.br" },
  { nome: "TJCE - Tribunal de Justiça do Ceará", url: "https://www.tjce.jus.br" },
  { nome: "TJDFT - Tribunal de Justiça do Distrito Federal e Territórios", url: "https://www.tjdft.jus.br" },
  { nome: "TJES - Tribunal de Justiça do Espírito Santo", url: "https://www.tjes.jus.br" },
  { nome: "TJGO - Tribunal de Justiça de Goiás", url: "https://www.tjgo.jus.br" },
  { nome: "TJMA - Tribunal de Justiça do Maranhão", url: "https://www.tjma.jus.br" },
  { nome: "TJMG - Tribunal de Justiça de Minas Gerais", url: "https://www.tjmg.jus.br" },
  { nome: "TJMS - Tribunal de Justiça de Mato Grosso do Sul", url: "https://www.tjms.jus.br" },
  { nome: "TJMT - Tribunal de Justiça de Mato Grosso", url: "https://www.tjmt.jus.br" },
  { nome: "TJPA - Tribunal de Justiça do Pará", url: "https://www.tjpa.jus.br" },
  { nome: "TJPB - Tribunal de Justiça da Paraíba", url: "https://www.tjpb.jus.br" },
  { nome: "TJPE - Tribunal de Justiça de Pernambuco", url: "https://www.tjpe.jus.br" },
  { nome: "TJPI - Tribunal de Justiça do Piauí", url: "https://www.tjpi.jus.br" },
  { nome: "TJPR - Tribunal de Justiça do Paraná", url: "https://www.tjpr.jus.br" },
  { nome: "TJRJ - Tribunal de Justiça do Rio de Janeiro", url: "https://www.tjrj.jus.br" },
  { nome: "TJRN - Tribunal de Justiça do Rio Grande do Norte", url: "https://www.tjrn.jus.br" },
  { nome: "TJRO - Tribunal de Justiça de Rondônia", url: "https://www.tjro.jus.br" },
  { nome: "TJRR - Tribunal de Justiça de Roraima", url: "https://www.tjrr.jus.br" },
  { nome: "TJRS - Tribunal de Justiça do Rio Grande do Sul", url: "https://www.tjrs.jus.br" },
  { nome: "TJSC - Tribunal de Justiça de Santa Catarina", url: "https://www.tjsc.jus.br" },
  { nome: "TJSE - Tribunal de Justiça de Sergipe", url: "https://www.tjse.jus.br" },
  { nome: "TJSP - Tribunal de Justiça de São Paulo", url: "https://www.tjsp.jus.br" },
  { nome: "TJTO - Tribunal de Justiça do Tocantins", url: "https://www.tjto.jus.br" },

  // Diários Oficiais
  { nome: "DJe - STF (Supremo Tribunal Federal)", url: "https://www.stf.jus.br/portal/jurisprudencia/diarioJustica.asp" },
  { nome: "DJe - STJ (Superior Tribunal de Justiça)", url: "https://www.stj.jus.br/sites/portalp/Paginas/Comunicacao/Diario-da-Justica-Eletronico.aspx" },
  { nome: "Diário da Justiça Federal (CJF/TRFs)", url: "https://www.cjf.jus.br/cjf/noticias/diario-da-justica-federal" },
  { nome: "DEJT - Justiça do Trabalho (TST/TRTs)", url: "https://dejt.jt.jus.br/dejt/f/n/diariocon" },
  { nome: "DJSP - Diário de Justiça de São Paulo", url: "https://www.djsp.jus.br" },
  { nome: "DJERJ - Diário de Justiça do Rio de Janeiro", url: "http://www4.tjrj.jus.br/ejud/" },
  { nome: "DJEMG - Diário de Justiça de Minas Gerais", url: "https://dje.tjmg.jus.br" }
];